<style>
    <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
    #top-nav > ul > li > a,
    #featured .record a,
    .site-page-pagination a,
    #top-nav > ul > li > a,
    #featured .record a,
    .site-page-pagination a,
    .results .result-title a {
        color: <?php echo $accentColor; ?>
    }
    
    p a,
    span a,
    .button,
    button,
    input[type="submit"],
    .secondary-nav li a,
    .pagination a.button,
    .item-pagination a,
    #featured .featured-meta h3,
    .advanced-search,
    .value a span,
    .sub-menu,
    .results .result-title a,
    .results > a,
    .results > ul + a,
    .results li > a:not(.resource-link),
    .breadcrumbs a,
    a.resource-link .resource-name,
    .property a:not(.resource-link) {
        background-color: <?php echo $accentColor; ?>;
    }
    <?php endif; ?>
    .banner {
        height: <?php echo ($bannerHeight !== '') ? $bannerHeight: 'auto'  ?>;
        align-items: <?php echo $bannerPosition; ?>;
    }
    <?php if ($bannerHeightMobile !== ''): ?>
        @media screen and (max-width:640px) {
            .banner {
                height: <?php echo $bannerHeightMobile; ?>;
            }
        }
    <?php endif; ?>
</style>
