<?php 
$bannerHeight = $this->themeSetting('banner_height');
$bannerHeightMobile = $this->themeSetting('banner_height_mobile');
$bannerPosition = ($this->themeSetting('banner_position')) ? str_replace('_','-', $this->themeSetting('banner_position')) : 'center';
$accentColor = $this->themeSetting('accent_color');
?>
<style>
    :root {
        --accent-color: <?php echo $accentColor; ?>;
    }

    .banner {
        height: <?php echo ($bannerHeight !== '') ? $bannerHeight: 'auto'  ?>;
        align-items: <?php echo $bannerPosition; ?>;
    }
    <?php if ($bannerHeightMobile !== ''): ?>
        @media screen and (max-width:640px) {
            .banner {
                height: <?php echo $bannerHeightMobile; ?>;
            }
        }
    <?php endif; ?>
</style>
