<?php $escape = $this->plugin('escapeHtml');?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item resource browse'); ?>
<?php if (isset($itemSet)): ?>
<?php $this->htmlElement('body')->appendAttribute('class', 'item-set show'); ?>
<?php endif; ?>

<?php if (isset($itemSet)): ?>
    <div class="show-header">
    <?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
    <h3><?php echo $this->translate('Item Set'); ?></h3>
    </div>
    <div class="metadata">
        <?php echo $itemSet->displayValues(); ?>
    </div>
    <?php echo $this->pageTitle($this->translate('Items'), 3); ?>
<?php else: ?>
    <?php echo $this->pageTitle($this->translate('Items'), 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>
<?php echo $this->hyperlink($this->translate('Advanced search'), $this->url(null, ['action' => 'search'], true), ['class' => 'advanced-search']); ?>
<?php echo $this->pagination(); ?>
<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list">
    <?php foreach ($items as $item): ?>
    <li class="item resource">
        <?php if ($primaryMedia = $item->primaryMedia()): ?>
        <img
            src="<?php echo $escape($primaryMedia->thumbnailUrl('medium')); ?>"
            title="<?php echo $escape($primaryMedia->displayTitle()); ?>"
            alt="<?php echo $escape($primaryMedia->mediaType()); ?> thumbnail"
        >
        <?php endif; ?>
        <h4><?php echo $item->link($item->displayTitle()); ?></h4>
        <?php if ($date = $item->value('dcterms:date')): ?>
        <div class="date"><?php echo $date; ?></div>
        <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<?php $this->trigger('view.browse.after'); ?>
<?php echo $this->pagination(); ?>


