<?php 
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$this->headScript()->prependFile($this->assetUrl('js/lightslider.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/lightgallery.min.js'));
$this->headLink()->prependStylesheet($this->assetUrl('css/lightgallery.min.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/lightslider.min.css'));
$subjects = $item->subjectValues();
$objects = $item->objectValues();
?>
<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<h3><?php echo $this->translate('Item'); ?></h3>
<?php $this->trigger('view.show.before'); ?>
<?php if ($item->media()): ?>
<ul id="itemfiles" class="media-list">
    <?php foreach ($item->media() as $media): ?>
        <?php $source = ($media->originalUrl()) ? $media->originalUrl() : $media->source(); ?>
        <li data-src="<?php echo $source; ?>" data-thumb="<?php echo $escape($media->thumbnailUrl('medium')); ?>" class="media resource">
            <?php echo $media->render(); ?>
        </li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<?php echo $item->displayValues(); ?>
<div class="property">
    <?php $itemSets = $item->itemSets(); ?>
    <?php if (count($itemSets) > 0): ?>
    <h4><?php echo $this->translate('Item Sets'); ?></h4>
    <?php foreach ($item->itemSets() as $itemSet): ?>
    <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
    <?php endforeach; ?>
    <?php endif; ?>
</div>

<?php if ($subjects || $objects): ?>
<div id="item-linked" class="property">
    <h4><?php echo $this->translate('Linked Resources'); ?></h4>
    <div class="value">
        <?php echo $item->displayLinkedResources(); ?>
    </div>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
<script src="<?php echo $this->assetUrl('js/lg-video.min.js'); ?>" type="text/javascript"></script>

<script>
    jQuery(document).ready(function() {
      $('#itemfiles').lightSlider({
          mode: 'fade',
          autoWidth: true,
          adaptiveHeight:false,
          gallery:true,
          item:1,
          loop:true,
          thumbItem:15,
          slideMargin:0,
          enableDrag: false,
          currentPagerPosition:'middle',
          onSliderLoad: function(el) {
              el.lightGallery({
                  selector: '#itemfiles .media',
                  youtubePlayerParams: {
                      modestbranding: 1,
                      showinfo: 0,
                      rel: 0,
                      controls: 1
                  },
                  vimeoPlayerParams: {
                      byline : 0,
                      portrait : 0,
                      color : 'A90707'     
                  },
              });
          }   
      });  
    });
</script>
