<?php 
$this->htmlElement('body')->appendAttribute('class', 'media resource show'); 
$mediaType = $media->mediaType();
$enableLightGallery = strpos($mediaType, 'image') !== false;
if ($enableLightGallery) {
    $this->headScript()->prependFile($this->assetUrl('js/lightslider.min.js'));
    $this->headScript()->prependFile($this->assetUrl('js/lightgallery.min.js'));
    $this->headLink()->prependStylesheet($this->assetUrl('css/lightgallery.min.css'));
    $this->headLink()->prependStylesheet($this->assetUrl('css/lightslider.min.css'));
}
?>

<?php echo $this->pageTitle($media->displayTitle(), 2); ?>
<h3><?php echo $this->translate('Media'); ?></h3>
<?php $this->trigger('view.show.before'); ?>
<?php echo $media->render(); ?>
<?php echo $media->displayValues(); ?>
<?php $this->trigger('view.show.after'); ?>
<?php if ($enableLightGallery): ?>
<script>
    jQuery(document).ready(function() {
      $('#itemfiles').lightSlider({
          mode: 'fade',
          autoWidth: true,
          adaptiveHeight:false,
          gallery:true,
          item:1,
          loop:true,
          thumbItem:15,
          slideMargin:0,
          enableDrag: false,
          currentPagerPosition:'middle',
          onSliderLoad: function(el) {
              el.lightGallery({
                  selector: '#itemfiles .media',
                  download: false,
                  zoom: true,
                  youtubePlayerParams: {
                      modestbranding: 1,
                      showinfo: 0,
                      rel: 0,
                      controls: 1
                  },
                  vimeoPlayerParams: {
                      byline : 0,
                      portrait : 0,
                      color : 'A90707'     
                  },
              });
          }   
      });  
    });
</script>
<?php endif; ?>