<?php 
$this->htmlElement('body')->appendAttribute('class', 'media resource show'); 
$mediaCaption = $this->themeSetting('media_caption');
$mediaType = $media->mediaType();
$enableLightGallery = strpos($mediaType, 'image') !== false;
?>

<?php echo $this->pageTitle($media->displayTitle(), 2); ?>
<h3><?php echo $this->translate('Media'); ?></h3>
<?php $this->trigger('view.show.before'); ?>
<?php if ($enableLightGallery): ?>
    <?php echo $this->LightGalleryOutput([$media]); ?>
<?php else: ?>
    <?php echo $media->render(); ?>
<?php endif; ?>
<?php echo $media->displayValues(); ?>
<?php $this->trigger('view.show.after'); ?>
