<div class="preview-block">

<?php if ($this->heading): ?>
<h2><?php echo $this->heading; ?></h2>
<?php endif; ?>

<ul class="resource-list preview">
<?php
$translate = $this->plugin('translate');
$headingTerm = $this->siteSetting('browse_heading_property_term');
foreach ($this->resources as $resource):
    $heading = $headingTerm ? $resource->value($headingTerm, ['default' => $translate('[Untitled]')]) : $resource->displayTitle();
?>
    <li class="item resource">
        <?php if (in_array('thumbnail', $this->components) && $primaryMedia = $resource->primaryMedia()): ?>
            <img
                src="<?php echo $this->escapeHtml($primaryMedia->thumbnailUrl('medium')); ?>"
                title="<?php echo $this->escapeHtml($primaryMedia->displayTitle()); ?>"
                alt="<?php echo $this->escapeHtml($primaryMedia->mediaType()); ?> thumbnail"
            >
        <?php endif; ?>
        <h4><?php
        if (in_array('resource-heading', $this->components)):
            echo $resource->link($heading);
        endif;?></h4>
        <?php if (in_array('resource-body', $this->components) && $date = $resource->value('dcterms:date')): ?>
        <div class="date"><?php echo $date; ?></div>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>

<?php
$linkText = $this->linkText == '' ? $this->translate('Browse all') : $this->linkText;
echo $this->hyperlink($linkText, $this->url(
    'site/resource', ['controller' => 'item', 'action' => 'browse'], ['query' => $this->query], true
), ['class' => 'button']);
?>

</div>
