<div class="preview-block">

<?php if ($this->heading): ?>
<h2><?php echo $this->heading; ?></h2>
<?php endif; ?>

<ul class="resource-list preview">
<?php 
$headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
foreach ($this->resources as $resource):
    $heading = $resource->value($headingTerm, ['default' => $this->translate('[Untitled]')]);
?>
    <li class="item resource">
        <?php if ($primaryMedia = $resource->primaryMedia()): ?>
            <img
                src="<?php echo $this->escapeHtml($primaryMedia->thumbnailUrl('medium')); ?>"
                title="<?php echo $this->escapeHtml($primaryMedia->displayTitle()); ?>"
                alt="<?php echo $this->escapeHtml($primaryMedia->mediaType()); ?> thumbnail"
            >
        <?php endif; ?>
        <h4><?php echo $resource->link($heading); ?></h4>
        <?php if ($date = $resource->value('dcterms:date')): ?>
        <div class="date"><?php echo $date; ?></div>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>

<?php
$linkText = $this->linkText == '' ? $this->translate('Browse all') : $this->linkText;
echo $this->hyperlink($linkText, $this->url(
    'site/resource', ['controller' => 'item', 'action' => 'browse'], ['query' => $this->query], true
), ['class' => 'button']);
?>

</div>
